# SPDX-FileCopyrightText: 2023 Matthias Riße <m.risse@fz-juelich.de>
#
# SPDX-License-Identifier: CC0-1.0

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: ci
    environment:
      name: pypi
      url: https://pypi.org/project/fsspec-git-annex
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v3
      - name: Publish package distributions to PyPI
        run: pdm publish
